// THIS FILE IS AUTOMATICALLY GENERATED BY $$KEH_BIND_PROGRAM$$
// SO YOU SHOULD NOT EDIT THIS FILE
// BY gunoodaddy, $$KEH_DATE$$
#pragma once

#include "bindutil.h"

class $$KEH_CLASSNAME$$
{
	public:

	$$KEH_CLASSNAME$$(JNIEnv *env, jobject obj, const $$KEH_STRUCTNAME$$ *data = NULL) : object(obj)
	{
		if(data)
			rawData = const_cast<$$KEH_STRUCTNAME$$ *>(data);
		else
			rawData = NULL;

		setEnv(env);
	}

	~$$KEH_CLASSNAME$$()
	{
		if(object)
			envJni->DeleteLocalRef(object);
	}

	static void initialize(JNIEnv *env)
	{
		classRef = env->FindClass("com/nhn/gametalk/api/type/$$KEH_JAVA_CLASSNAME$$");
		classRef = (jclass)env->NewGlobalRef(classRef);

$$KEH_FID_ASSIGN_REGION$$

		midInit = env->GetMethodID(classRef, "<init>", "()V");
	}

	void setEnv(JNIEnv *env)
	{
		this->envJni = env;
	}

	jobject makeObject(bool fillEmptyData = false)
	{
		if(object)
			return object;

		object = envJni->NewObject(classRef, midInit);

		if(false == fillEmptyData)
		{
$$KEH_CALL_SETTER_METHOD_REGION$$
		}
		return object;
	}

$$KEH_GETTER_METHOD_REGION$$
$$KEH_SETTER_METHOD_REGION$$
$$KEH_CONVERT_DATA_FUNCTION$$

public:
	static jclass classRef;

$$KEH_DECLARE_JFIILDID_REGION$$

	static jmethodID midInit;
private:
	jobject object;
	JNIEnv *envJni;
	$$KEH_STRUCTNAME$$ *rawData;
};



